export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_POSTS = "UPDATE_POSTS";
export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_POST_COMMENTS = "UPDATE_POST_COMMENTS";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const REMOVE_POST = "REMOVE_POST";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
